# Generated by Django 4.0.3 on 2022-03-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_staff_remove_user_role_delete_role_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_admin',
        ),
    ]
