# Generated by Django 4.0.3 on 2022-03-13 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_staff_home_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.location')),
            ],
        ),
    ]
